//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefinityFirst.Sample.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.CountryRegionCurrency = new HashSet<CountryRegionCurrency>();
            this.FromCurrencyRate = new HashSet<CurrencyRate>();
            this.ToCurrencyRate = new HashSet<CurrencyRate>();
        }
    
        public string CurrencyCode { get; set; }
        public string Name { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<CountryRegionCurrency> CountryRegionCurrency { get; set; }
        public virtual ICollection<CurrencyRate> FromCurrencyRate { get; set; }
        public virtual ICollection<CurrencyRate> ToCurrencyRate { get; set; }
    }
}
